title: CV | Jeremy Damour
description:  Jeremy Damour - curriculum vitae
domain: start974.github.io
url: https://start974.github.io
baseurl: /src
theme_skin: blue

sass:
  sass_dir: _sass
  style: compressed

plugins:
    - jekyll-minifier

include:
  - _data/data.yml

exclude:
  - LICENCE
  - README.md
  - shell.nix
