title: CV | Jérémy Damour
description: Jérémy Damour - curriculum vitae
domain: start974.github.io
url: https://start974.github.io
baseurl: /cv
theme_skin: blue

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-minifier
  - jekyll-multiple-languages-plugin

languages: ["fr", "en"]

exclude:
  - LICENSE
  - README.md
